### ISSUE TITLE
Error: Could not find a valid build

### ISSUE THREAD

**Issue by throne1986** [grouparoo/grouparoo#1025]
I have followed all instructions in docs about running grouparoo on local machine in Linux system but unfortunatelly when I run `npm start` i get the following error 

```

2020-11-26T11:35:53.887Z - info: using path "/var/www/intergration/node_modules/@grouparoo/core/api/files/development" for Grouparoo file storage 
modified your next.js environment with /var/www/intergration/.env
2020-11-26T11:35:54.142Z - emerg: Exception occurred in initializer `next` during start 
2020-11-26T11:35:54.142Z - emerg: Error with initializer step: "start" 
2020-11-26T11:35:54.143Z - emerg: Error: Could not find a valid build in the '/var/www/intergration/node_modules/@grouparoo/core/web/.next' directory! Try building your app with 'next build' before starting the server.
    at Server.readBuildId (/var/www/intergration/node_modules/next/dist/next-server/server/next-server.js:137:355)
    at new Server (/var/www/intergration/node_modules/next/dist/next-server/server/next-server.js:3:120)
    at Object.createServer [as default] (/var/www/intergration/node_modules/next/dist/server/next.js:2:638)
    at Next.start (/var/www/intergration/node_modules/ah-next-plugin/dist/initializers/next.js:60:49)
    at async Object.startFunction (/var/www/intergration/node_modules/actionhero/dist/classes/process.js:123:29)
    at async Object.asyncWaterfall (/var/www/intergration/node_modules/actionhero/dist/modules/utils/asyncWaterfall.js:47:23)
    at async Process.start (/var/www/intergration/node_modules/actionhero/dist/classes/process.js:198:13)
    at async main (/var/www/intergration/node_modules/@grouparoo/core/api/dist/grouparoo.js:31:5) 
2020-11-26T11:35:54.143Z - notice: stopping process... 
2020-11-26T11:35:54.151Z - info: actionhero member 192.168.254.128 has joined the cluster 
2020-11-26T11:35:54.247Z - notice: Stopping server: web 
2020-11-26T11:35:54.248Z - notice: Stopping server: websocket 
2020-11-26T11:35:54.257Z - notice: *** Actionhero Stopped *** 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grouparoo/app-example@0.0.1 start: `cd node_modules/@grouparoo/core && ./api/bin/start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @grouparoo/app-example@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-26T11_35_55_435Z-debug.log
root@bonge-virtual-machine:/var/www/intergration
```
what do I need to do to solve this problem?

**Comment by evantahler** [comment]
Hi @throne1986!

Can you let us know if there were any errors that happened when you ran `npm install`?

As part of `npm install`, `npm run prepare` should have also run, would would generate that "valid build" for the web UI.  Try running `npm run prepare` again.

**Comment by evantahler** [comment]
Hi @throne1986 - Do you have any updates for us?  Were you able to get it working?

**Comment by evantahler** [comment]
Closing due to lack of comment

**Comment by throne1986** [comment]
Hi @evantahler I am very sorry for the late reply, I have family problems, tried running `npm run prepare` but I get the following error

```
> cd node_modules/@grouparoo/core && npm run prepare


> @grouparoo/core@0.1.25 prepare /var/www/intergration/node_modules/@grouparoo/core
> npm run build-api && npm run build-web && npm run thank-you


> @grouparoo/core@0.1.25 build-api /var/www/intergration/node_modules/@grouparoo/core
> ./api/bin/build

Building @grouparoo/core API...
@grouparoo/core API built in 22s


> @grouparoo/core@0.1.25 build-web /var/www/intergration/node_modules/@grouparoo/core
> cd web && next build

modified your next.js environment with /var/www/intergration/.env
info  - Using external babel configuration from /var/www/intergration/node_modules/@grouparoo/core/web/.babelrc.js
info  - Creating an optimized production build  
Failed to compile.

./scss/grouparoo.scss
Error: Missing binding /var/www/intergration/node_modules/node-sass/vendor/linux-x64-72/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.


> Build error occurred
Error: > Build failed because of webpack errors
    at build (/var/www/intergration/node_modules/next/dist/build/index.js:15:918)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grouparoo/core@0.1.25 build-web: `cd web && next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @grouparoo/core@0.1.25 build-web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-08T16_21_58_815Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grouparoo/core@0.1.25 prepare: `npm run build-api && npm run build-web && npm run thank-you`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @grouparoo/core@0.1.25 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-08T16_21_58_878Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grouparoo/app-example@0.0.1 prepare: `cd node_modules/@grouparoo/core && npm run prepare`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @grouparoo/app-example@0.0.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-12-08T16_21_58_934Z-debug.log
root@bonge-virtual-machine:/var/www/intergration# 
```

thanks

**Comment by evantahler** [comment]
I'm sorry to hear that! I hope everything will be OK soon.

Thank you for sharing the whole error.  This confirms that there was a problem with your original run of `npm install`.  Did you follow the instructions about how to rebuild `node-sass`:

> This usually happens because your environment has changed since running `npm install`.
> Run `npm rebuild node-sass` to download the binding for your current environment.

Alternatively, you could just remove `node_modules` within your Grouparoo project and `nom install` again to re-download all the dependencies.

**Comment by evantahler** [comment]
@throne1986 I'm going to convert this to a Discussion because I don't think this is necessarily an Issue with Grouparoo.
