### ISSUE TITLE
Latest version of Grouparoo crashing when built with `@grouparoo/ui-confing` package present

### ISSUE THREAD

**Issue by evantahler** [grouparoo/grouparoo#2078]
**Describe the bug**
Grouparoo crashes on Boot with the following error:

```
TypeError: Cannot read property 'path' of undefined
    at Object.general (/app/node_modules/@grouparoo/core/dist/config/api.js:70:36)
    at Object.hashMerge (/app/node_modules/actionhero/dist/modules/utils/hashMerge.js:50:32)
    at loadConfigFile (/app/node_modules/actionhero/dist/modules/config.js:99:40)
    at loadConfigDirectory (/app/node_modules/actionhero/dist/modules/config.js:114:17)
    at /app/node_modules/actionhero/dist/modules/config.js:160:36
    at Array.map (<anonymous>)
    at buildConfig (/app/node_modules/actionhero/dist/modules/config.js:160:25)
    at Object.<anonymous> (/app/node_modules/actionhero/dist/modules/config.js:174:18)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)

Error: ENOENT: no such file or directory, lstat '/node_modules'
    at Object.realpathSync (node:fs:1807:7)
    at Object.getPluginManifest (/app/node_modules/@grouparoo/core/dist/utils/pluginDetails.js:83:25)
    at getNextRootPath (/app/node_modules/@grouparoo/core/dist/config/next.js:28:44)
    at Object.next (/app/node_modules/@grouparoo/core/dist/config/next.js:13:30)
    at Object.hashMerge (/app/node_modules/actionhero/dist/modules/utils/hashMerge.js:50:32)
    at loadConfigFile (/app/node_modules/actionhero/dist/modules/config.js:99:40)
    at loadConfigDirectory (/app/node_modules/actionhero/dist/modules/config.js:114:17)
    at /app/node_modules/actionhero/dist/modules/config.js:160:36
    at Array.map (<anonymous>)
    at buildConfig (/app/node_modules/actionhero/dist/modules/config.js:160:25)
```

**To Reproduce**

Using this `package.json`, build a docker image and see the error

```json
{
  "author": "Grouparoo Inc <hello@grouparoo.com>",
  "name": "@grouparoo/app-example-docker",
  "description": "An example Grouparoo Deployment",
  "version": "0.0.1",
  "license": "MPL-2.0",
  "private": true,
  "dependencies": {
    "@grouparoo/bigquery": "0.5.1",
    "@grouparoo/core": "0.5.1",
    "@grouparoo/csv": "0.5.1",
    "@grouparoo/files-s3": "0.5.1",
    "@grouparoo/google-sheets": "0.5.1",
    "@grouparoo/hubspot": "0.5.1",
    "@grouparoo/logger": "0.5.1",
    "@grouparoo/mailchimp": "0.5.1",
    "@grouparoo/mysql": "0.5.1",
    "@grouparoo/postgres": "0.5.1",
    "@grouparoo/salesforce": "0.5.1",
    "@grouparoo/snowflake": "0.5.1",
    "@grouparoo/ui-community": "0.5.1",
    "@grouparoo/zendesk": "0.5.1"
  },
  "scripts": {
    "start": "cd node_modules/@grouparoo/core && ./bin/start",
    "test": "./__tests__/integration"
  },
  "grouparoo": {
    "plugins": [
      "@grouparoo/bigquery",
      "@grouparoo/csv",
      "@grouparoo/files-s3",
      "@grouparoo/google-sheets",
      "@grouparoo/hubspot",
      "@grouparoo/logger",
      "@grouparoo/mailchimp",
      "@grouparoo/mysql",
      "@grouparoo/postgres",
      "@grouparoo/salesforce",
      "@grouparoo/snowflake",
      "@grouparoo/ui-community",
      "@grouparoo/zendesk"
    ],
    "includedFiles": [
      "assets"
    ]
  }
}
```

**Expected behavior**

**Environment (please complete the following information):**
 - Grouparoo Version: 0.5.1
 - Node.js Version: v15.14.0
 - NPM Version: 7.11.2

**Additional context**

**Comment by evantahler** [comment]
This bug occurs when `@grouparoo/ui-config` is present within `package.json`'s "devDependencies", and you've run either `npm install --production` or `npm run prune` - Grouparoo would be expecting the ui-config plugin to exist, but it has been removed by NPM
