### ISSUE TITLE
When there is a destination tracking all groups, a new group cannot be created

### ISSUE THREAD

**Issue by evantahler** [grouparoo/grouparoo#372]

**Comment by andyjih** [comment]
```
2020-06-18T18:50:42.431Z - info: [ action @ web ] to=127.0.0.1 action=group:create params={"name":"another one","type":"calculated","state":"draft","csrfToken":"[FILTERED]","action":"group:create","apiVersion":"1","matchType":"all"} duration=588 error=Error: cannot find Group grp_e7c8fac8-fdf5-4db0-b4f8-27dce88f32b0 
2020-06-18T18:50:42.431Z - error:  ! Error: cannot find Group grp_e7c8fac8-fdf5-4db0-b4f8-27dce88f32b0 
2020-06-18T18:50:42.431Z - error:  !     at Function.findByGuid (/Users/andyjih/projects/grouparoo/core/api/src/models/Group.ts:832:13) 
2020-06-18T18:50:42.431Z - error:  !     at runMicrotasks (<anonymous>) 
2020-06-18T18:50:42.431Z - error:  !     at processTicksAndRejections (internal/process/task_queues.js:97:5) 
2020-06-18T18:50:42.431Z - error:  !     at Function.updateGroupMembersOnCreate (/Users/andyjih/projects/grouparoo/core/api/src/models/DestinationGroup.ts:38:19) 
2020-06-18T18:50:42.431Z - error:  ! From previous event: 
2020-06-18T18:50:42.431Z - error:  !     at Function.runHooks (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize/lib/hooks.js:124:20) 
2020-06-18T18:50:42.431Z - error:  !     at Function.Model.<computed> [as runHooks] (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize-typescript/dist/model/model/model.js:117:28) 
2020-06-18T18:50:42.431Z - error:  !     at /Users/andyjih/projects/grouparoo/core/node_modules/sequelize/lib/model.js:4074:37 
2020-06-18T18:50:42.431Z - error:  ! From previous event: 
2020-06-18T18:50:42.431Z - error:  !     at /Users/andyjih/projects/grouparoo/core/node_modules/sequelize/lib/model.js:4071:10 
2020-06-18T18:50:42.431Z - error:  ! From previous event: 
2020-06-18T18:50:42.431Z - error:  !     at DestinationGroup.save (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize/lib/model.js:3966:8) 
2020-06-18T18:50:42.431Z - error:  !     at Function.create (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize/lib/model.js:2230:8) 
2020-06-18T18:50:42.431Z - error:  !     at Function.Model.<computed> (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize-typescript/dist/model/model/model.js:117:28) 
2020-06-18T18:50:42.431Z - error:  !     at Function.Model.<computed> [as create] (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize-typescript/dist/model/model/model.js:129:28) 
2020-06-18T18:50:42.431Z - error:  !     at /Users/andyjih/projects/grouparoo/core/node_modules/sequelize/lib/model.js:2336:19 
2020-06-18T18:50:42.431Z - error:  !     at processImmediate (internal/timers.js:456:21) 
2020-06-18T18:50:42.431Z - error:  !     at process.topLevelDomainCallback (domain.js:137:15) 
2020-06-18T18:50:42.431Z - error:  ! From previous event: 
2020-06-18T18:50:42.432Z - error:  !     at Function.findOrCreate (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize/lib/model.js:2324:8) 
2020-06-18T18:50:42.432Z - error:  !     at Function.Model.<computed> (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize-typescript/dist/model/model/model.js:117:28) 
2020-06-18T18:50:42.432Z - error:  !     at Function.Model.<computed> [as findOrCreate] (/Users/andyjih/projects/grouparoo/core/node_modules/sequelize-typescript/dist/model/model/model.js:129:28) 
2020-06-18T18:50:42.432Z - error:  !     at Function.linkToDestinationsTrackingAllGroups (/Users/andyjih/projects/grouparoo/core/api/src/models/Group.ts:162:30) 
2020-06-18T18:50:42.432Z - error:  !     at runMicrotasks (<anonymous>) 
2020-06-18T18:50:42.432Z - error:  !     at processTicksAndRejections (internal/process/task_queues.js:97:5) 
```
