### ISSUE TITLE
Grouparoo cannot be installed - TypeError: glob pattern string required

### ISSUE THREAD

**Issue by evantahler** [grouparoo/grouparoo#841]
```
2020-10-12T07:29:53.295Z - notice: Starting Grouparoo 0.1.17 on node.js v12.18.4 
2020-10-12T07:29:54.111Z - emerg: Exception occurred in initializer `sequelize` during load 
2020-10-12T07:29:54.112Z - emerg: Error with initializer step: "initialize" 
2020-10-12T07:29:54.112Z - emerg: TypeError: glob pattern string required
    at new Minimatch (/grouparoo/node_modules/minimatch/minimatch.js:116:11)
    at setopts (/grouparoo/node_modules/glob/common.js:118:20)
    at new Glob (/grouparoo/node_modules/glob/glob.js:135:3)
    at glob (/grouparoo/node_modules/glob/glob.js:75:10)
    at internal/util.js:297:30
    at new Promise (<anonymous>)
    at glob (internal/util.js:296:12)
    at Umzug.migrations (/grouparoo/node_modules/ah-sequelize-plugin/node_modules/umzug/lib/umzug.js:175:33)
    at Umzug._pending (/grouparoo/node_modules/ah-sequelize-plugin/node_modules/umzug/lib/umzug.js:62:69)
    at eligibleMigrations (/grouparoo/node_modules/ah-sequelize-plugin/node_modules/umzug/lib/umzug.js:85:43)
    at Umzug.up (/grouparoo/node_modules/ah-sequelize-plugin/node_modules/umzug/lib/umzug.js:92:35)
    at SequelizeInitializer.migrate (/grouparoo/node_modules/ah-sequelize-plugin/dist/initializers/sequelize.js:29:29)
    at SequelizeInitializer.initialize (/grouparoo/node_modules/ah-sequelize-plugin/dist/initializers/sequelize.js:19:20)
    at async Object.initializeFunction (/grouparoo/node_modules/actionhero/dist/classes/process.js:100:29)
    at async Object.asyncWaterfall (/grouparoo/node_modules/actionhero/dist/modules/utils/asyncWaterfall.js:47:23)
    at async Process.initialize (/grouparoo/node_modules/actionhero/dist/classes/process.js:169:13)
    at async Process.start (/grouparoo/node_modules/actionhero/dist/classes/process.js:178:13)
    at async main (/grouparoo/node_modules/@grouparoo/core/api/dist/grouparoo.js:34:5) 
2020-10-12T07:29:54.113Z - crit: Cannot shut down actionhero, not running 
```

**Comment by evantahler** [comment]
This bug can be traced back to a breaking change in the `umzug` package, which is used to run database migrations.  See https://github.com/actionhero/ah-sequelize-plugin/pull/206 for more information

The dependency chain is:
@grouparoo/core -> sequelize / ah-sequelize-plugin -> umzug
